name: ${project.name}
version: ${project.version}
description: ${project.description}

authors: [Newt, Blu, PlunderSeas Staff]
main: me.newt.plunderseas.PS
website: https://github.com/JustDJplease/plunderseas
depend: [PreciousStones, Vault, FastAsyncWorldEdit]

api-version: 1.13