name: ${project.name}
version: ${project.version}
description: ${project.description}

authors: [Newt, Blu, PlunderSeas Staff]
main: me.newt.plunderseas.PlunderSeas
website: https://github.com/JustDJplease/plunderseas
depend: [Vault]

api-version: 1.16